deployment:
  tasks:
    - export DEPLOYPATH=/home/fenfitnepal/dahal-handicraft/
    - /bin/cp -r website $DEPLOYPATH
    - /bin/cp -r root $DEPLOYPATH
    - /bin/cp -r account $DEPLOYPATH
    - /bin/cp -r media $DEPLOYPATH
  
  